LOAD DATA LOCAL INFILE 'course.csv' INTO TABLE course FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'degree.csv' INTO TABLE degree FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'hasPrereq.csv' INTO TABLE hasPrereq FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'hasReq.csv' INTO TABLE hasReq FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'hasElec.csv' INTO TABLE hasElec FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'elecBucket.csv' INTO TABLE elecBucket FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;